# Model arguments
model_name_or_path: microsoft/Phi-3-mini-128k-instruct
torch_dtype: null
use_flash_attention_2: false

# Data training arguments
dataset_mixer:
  mlabonne/orpo-dpo-mix-40k: 1.0
dataset_splits:
- train
preprocessing_num_workers: 12

# CPOTrainer arguments
bf16: true
beta: 10
simpo_gamma: 5.4
cpo_alpha: 0.05
loss_type: simpo
do_eval:
evaluation_strategy:
eval_steps:
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id:
learning_rate: 1.0e-6
log_level: info
logging_steps: 1
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/Phi-3-mini-128K-cpo-simpo
run_name: Phi-3-mini-128K-cpo-simpo
per_device_train_batch_size: 8
per_device_eval_batch_size:
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
